server:
  port: 8081
  error:
    include-stacktrace: never
  servlet:
    session:
      timeout: 5m
spring:
  datasource:
    url: jdbc:ucanaccess://Path-to-DB
    driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
